### ISSUE TITLE
bbjapi() and BBjAPI()

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#124] opened 2024-06-05 19:45 UTC
When using bbjapi() instead of BBjAPI() (which is valid in BBj, and prevalent in documentation samples), the plug-in fails to detect the derived types, like 

```
API! = bbjapi()
sg! = API!.openSysGui("X0")
```

**Comment by dhuebner** [comment] 2024-08-21 13:33
Close as duplicate of #28

**Closed by dhuebner** 2024-08-21 13:33 UTC
Labels: duplicate
