### ISSUE TITLE
support MODE= in MSGBOX

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#96] opened 2023-09-21 18:45 UTC
```
temp = msgbox("Hello from BBj's " + client$ + " client!", BBjSysGui.MSGBOX_ICON_INFORMATION, "Greetings", MODE="theme=primary")
```

**Comment by dhuebner** [comment] 2023-10-04 13:00
@StephanWald 
Duplicate of  #45 ?

**Closed** 2023-10-05 14:49 UTC
Labels: duplicate
